# Generated by Django 3.2.6 on 2024-12-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
    ]
